# Form implementation generated from reading ui file 'interface.ui'
#
# Created by: PyQt6 UI code generator 6.6.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(341, 289)
        Dialog.setFocusPolicy(QtCore.Qt.FocusPolicy.TabFocus)
        self.layoutWidget = QtWidgets.QWidget(parent=Dialog)
        self.layoutWidget.setGeometry(QtCore.QRect(40, 10, 261, 261))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButtonSelecionePasta = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.pushButtonSelecionePasta.setObjectName("pushButtonSelecionePasta")
        self.verticalLayout.addWidget(self.pushButtonSelecionePasta)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(parent=self.layoutWidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.lineEditLink = QtWidgets.QLineEdit(parent=self.layoutWidget)
        self.lineEditLink.setObjectName("lineEditLink")
        self.horizontalLayout_2.addWidget(self.lineEditLink)
        self.pushButtonBaixar = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.pushButtonBaixar.setObjectName("pushButtonBaixar")
        self.horizontalLayout_2.addWidget(self.pushButtonBaixar)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.pushButtonSelecioneArquivo = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.pushButtonSelecioneArquivo.setObjectName("pushButtonSelecioneArquivo")
        self.verticalLayout.addWidget(self.pushButtonSelecioneArquivo)
        self.pushButtonTranscrever = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.pushButtonTranscrever.setObjectName("pushButtonTranscrever")
        self.verticalLayout.addWidget(self.pushButtonTranscrever)
        self.pushButtonTraduzir = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.pushButtonTraduzir.setObjectName("pushButtonTraduzir")
        self.verticalLayout.addWidget(self.pushButtonTraduzir)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.pushButtonSelecionePasta, self.pushButtonSelecioneArquivo)
        Dialog.setTabOrder(self.pushButtonSelecioneArquivo, self.pushButtonTranscrever)
        Dialog.setTabOrder(self.pushButtonTranscrever, self.pushButtonTraduzir)
        Dialog.setTabOrder(self.pushButtonTraduzir, self.lineEditLink)
        Dialog.setTabOrder(self.lineEditLink, self.pushButtonBaixar)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Whisper"))
        self.pushButtonSelecionePasta.setText(_translate("Dialog", "Selecione a pasta de destino"))
        self.label_2.setText(_translate("Dialog", "Link:"))
        self.pushButtonBaixar.setText(_translate("Dialog", "Baixar"))
        self.pushButtonSelecioneArquivo.setText(_translate("Dialog", "Selecione o arquivo"))
        self.pushButtonTranscrever.setText(_translate("Dialog", "Transcrever"))
        self.pushButtonTraduzir.setText(_translate("Dialog", "Traduzir (pt)"))
